CREATE DATABASE IF NOT EXISTS learninglabs;
USE learninglabs;

CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    deadline DATE DEFAULT CURENT_TIMESTAMP, 
);